name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet Issue or PR
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            🎉 Thank you for opening this issue! We appreciate your contribution and will review it soon.
          pr-message: |
            🎉 Thank you for your pull request! We will review it as soon as possible.